spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdata_jpa?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        hbm2ddl:
#          auto: update #第一次加载 Hibernate 时根据 model 类会自动建立起表的结构（前提是先建立好数据库），以后加载 Hibernate 时根据 model 类自动更新表结构，即使表结构改变了，但表中的行仍然存在，不会删除以前的行。
        dialect: org.hibernate.dialect.MySQL8Dialect  #dialect 主要是指定生成表名的存储引擎为 InnoDB
        format_sql: true
    show-sql: true  #show-sql 是否在日志中打印出自动生成的 SQL，方便调试的时候查看

  #设定ftl文件路径
  freemarker:
    template-loader-path: classpath:/templates/
  #设定静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .ftl

##端口号
server:
  port: 8888
